In [2]:
import os
import json
import pandas as pd
from pathlib import Path
import mysql.connector as sql
import streamlit as st
from streamlit_option_menu import option_menu

In [5]:
#agg_Transaction

Path = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/aggregated/transaction/country/india/state/"
Agg_Trans_list = os.listdir(Path)


# Initialize the dictionary to store the data
clm = {"State": [], "Year": [], "Quarter": [], "Transaction_type": [], "Transaction_Count": [], "Transaction_Amount": []}

# Loop through the states
for state in Agg_Trans_list:
    state_list=Path+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Agg_Trans_Data = json.load(JF)

            # Extract the data from the JSON object
            for transaction in Agg_Trans_Data["data"]["transactionData"]:
                clm["Transaction_type"].append(transaction["name"])
                clm["Transaction_Count"].append(transaction["paymentInstruments"][0]["count"])
                clm["Transaction_Amount"].append(transaction["paymentInstruments"][0]["amount"])
                clm["State"].append(state)
                clm["Year"].append(year)
                clm["Quarter"].append(int(jfile.strip(".json")))

# Create the DataFrame
Agg_Trans = pd.DataFrame(clm)
Agg_Trans["State"]=Agg_Trans["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Agg_Trans["State"]=Agg_Trans["State"].str.replace("-", " ")
Agg_Trans["State"]=Agg_Trans["State"].str.title()
Agg_Trans["State"]=Agg_Trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Agg_Trans["States"].unique()

In [ ]:
Agg_Trans

In [6]:
#Agg_user

Path1 = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/aggregated/user/country/india/state/"
Agg_user_list = os.listdir(Path1)

# Initialize the dictionary to store the data
clm1 = {"State": [], "Year": [], "Quarter": [], "Brand": [], "Transaction_Count": [], "Percentage": []}

# Loop through the State
for state in Agg_user_list:
    state_list=Path1+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Agg_User_Data = json.load(JF)
            try:
                for user in Agg_User_Data["data"]["usersByDevice"]:
                    brand=user["brand"]
                    count=user["count"]
                    percentage=user["percentage"]
                    clm1["Brand"].append(brand)
                    clm1["Transaction_Count"].append(count)
                    clm1["Percentage"].append(percentage)
                    clm1["State"].append(state)
                    clm1["Year"].append(year)
                    clm1["Quarter"].append(int(jfile.strip(".json")))
            except:
                pass
Agg_user=pd.DataFrame(clm1)
Agg_user["State"]=Agg_user["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Agg_user["State"]=Agg_user["State"].str.replace("-", " ")
Agg_user["State"]=Agg_user["State"].str.title()
Agg_user["State"]=Agg_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Agg_user["State"].unique()

array(['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
       'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal'], dtype=object)

In [ ]:
Agg_user

,State,Year,Quarter,Brand,Transaction_Count,Percentage
0,Andaman & Nicobar Islands,2018,1,Xiaomi,1665,0.247033
1,Andaman & Nicobar Islands,2018,1,Samsung,1445,0.214392
2,Andaman & Nicobar Islands,2018,1,Vivo,982,0.145697
3,Andaman & Nicobar Islands,2018,1,Oppo,501,0.074332
4,Andaman & Nicobar Islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,West Bengal,2022,1,Lenovo,330017,0.015056
6728,West Bengal,2022,1,Infinix,284678,0.012987
6729,West Bengal,2022,1,Asus,280347,0.012790
6730,West Bengal,2022,1,Apple,277752,0.012671
6731,West Bengal,2022,1,Others,2196334,0.100199

In [7]:
#Map_Trans

Path2 = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/map/transaction/hover/country/india/state/"
Map_trans_list = os.listdir(Path2)

# Initialize the dictionary to store the data
clm2 = {"State": [], "Year": [], "Quarter": [], "District": [], "Transaction_Count": [], "Transaction_Amount": []}

# Loop through the states
for state in Map_trans_list:
    state_list=Path2+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Map_Trans_Data = json.load(JF)
            
            for Map in Map_Trans_Data["data"]["hoverDataList"]:
                Name=Map["name"]
                count=Map["metric"][0]["count"]
                Amount=Map["metric"][0]["amount"]
                clm2["District"].append(Name)
                clm2["Transaction_Count"].append(count)
                clm2["Transaction_Amount"].append(Amount)
                clm2["State"].append(state)
                clm2["Year"].append(year)
                clm2["Quarter"].append(int(jfile.strip(".json")))

Map_Trans=pd.DataFrame(clm2)
Map_Trans["State"]=Map_Trans["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Map_Trans["State"]=Map_Trans["State"].str.replace("-", " ")
Map_Trans["State"]=Map_Trans["State"].str.title()
Map_Trans["District"]=Map_Trans["District"].str.title()
Map_Trans["State"]=Map_Trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Map_Trans["District"].unique()

array(['North And Middle Andaman District', 'South Andaman District',
       'Nicobars District', 'East Godavari District',
       'Srikakulam District', 'Spsr Nellore District',
       'Vizianagaram District', 'Visakhapatnam District',
       'Prakasam District', 'Anantapur District', 'Ysr District',
       'West Godavari District', 'Kurnool District', 'Chittoor District',
       'Guntur District', 'Krishna District',
       'Lower Dibang Valley District', 'Lower Subansiri District',
       'Longding District', 'West Siang District', 'Kamle District',
       'Upper Siang District', 'Tirap District', 'Papum Pare District',
       'Kurung Kumey District', 'Siang District', 'Lower Siang District',
       'Kra Daadi District', 'Changlang District',
       'Pakke Kessang District', 'Dibang Valley District',
       'West Kameng District', 'East Siang District',
       'Upper Subansiri District', 'East Kameng District',
       'Lohit District', 'Lepa Rada District', 'Tawang District',
       'Namsai District', 'Anjaw District', 'Shi Yomi District',
       'Tinsukia District', 'Lakhimpur District', 'Kamrup District',
       'Kokrajhar District', 'Karbi Anglong District',
       'Sivasagar District', 'Dibrugarh District',
       'South Salmara Mancachar District', 'Nagaon District',
       'Dhubri District', 'Golaghat District', 'Udalguri District',
       'Majuli District', 'Sonitpur District', 'Hojai District',
       'Marigaon District', 'Chirang District', 'Cachar District',
       'Nalbari District', 'West Karbi Anglong District',
       'Dhemaji District', 'Karimganj District', 'Bongaigaon District',
       'Dima Hasao District', 'Baksa District', 'Charaideo District',
       'Darrang District', 'Kamrup Metropolitan District',
       'Hailakandi District', 'Barpeta District', 'Goalpara District',
       'Biswanath District', 'Jorhat District', 'Madhepura District',
       'Purnia District', 'Nalanda District', 'Buxar District',
       'Darbhanga District', 'Nawada District', 'Jamui District',
       'Sheikhpura District', 'Siwan District', 'Muzaffarpur District',
       'Patna District', 'Jehanabad District', 'Rohtas District',
       'Begusarai District', 'Supaul District', 'Sitamarhi District',
       'Saran District', 'Arwal District', 'Vaishali District',
       'Pashchim Champaran District', 'Gopalganj District',
       'Lakhisarai District', 'Aurangabad District',
       'Kaimur Bhabua District', 'Araria District', 'Munger District',
       'Katihar District', 'Khagaria District', 'Saharsa District',
       'Bhagalpur District', 'Madhubani District', 'Kishanganj District',
       'Gaya District', 'Samastipur District', 'Banka District',
       'Purbi Champaran District', 'Sheohar District', 'Bhojpur District',
       'Chandigarh District', 'Dhamtari District', 'Korba District',
       'Surajpur District', 'Baloda Bazar District', 'Sukma District',
       'Raigarh District', 'Janjgir Champa District', 'Jashpur District',
       'Balod District', 'Kabirdham District', 'Surguja District',
       'Dantewada District', 'Gariyaband District', 'Durg District',
       'Rajnandgaon District', 'Raipur District', 'Narayanpur District',
       'Kanker District', 'Korea District', 'Mungeli District',
       'Bilaspur District', 'Balrampur District', 'Bijapur District',
       'Bemetara District', 'Bastar District', 'Kondagaon District',
       'Mahasamund District', 'Diu District', 'Daman District',
       'Dadra And Nagar Haveli District', 'South District',
       'Central District', 'New Delhi District', 'West District',
       'South West District', 'South East Delhi District',
       'Shahdara District', 'North East District', 'East District',
       'North West District', 'North District', 'North Goa District',
       'South Goa District', 'Anand District', 'Jamnagar District',
       'Devbhumi Dwarka District', 'Rajkot District',
       'Aravallis District', 'Chhotaudepur District', 'Botad District',
       'Bharuch District', 'Bhavnagar District', 'Junagadh District',
       'Mahesana District', 'The Dangs District', 'Kheda District',
       'Surat District', 'Porbandar District', 'Gandhinagar District',
       'Panch Mahals District', 'Narmada District',
       'Gir Somnath District', 'Valsad District', 'Mahisagar District',
       'Sabar Kantha District', 'Tapi District', 'Vadodara District',
       'Banas Kantha District', 'Amreli District', 'Ahmadabad District',
       'Dohad District', 'Navsari District', 'Patan District',
       'Kachchh District', 'Surendranagar District', 'Morbi District',
       'Yamunanagar District', 'Sonipat District', 'Jind District',
       'Rohtak District', 'Faridabad District', 'Mahendragarh District',
       'Hisar District', 'Karnal District', 'Fatehabad District',
       'Palwal District', 'Charkhi Dadri District', 'Ambala District',
       'Rewari District', 'Panchkula District', 'Bhiwani District',
       'Sirsa District', 'Mewat District', 'Panipat District',
       'Gurugram District', 'Kaithal District', 'Kurukshetra District',
       'Jhajjar District', 'Solan District', 'Sirmaur District',
       'Shimla District', 'Hamirpur District', 'Una District',
       'Kangra District', 'Kullu District', 'Mandi District',
       'Lahul And Spiti District', 'Chamba District', 'Kinnaur District',
       'Muzaffarabad District', 'Doda District', 'Samba District',
       'Mirpur District', 'Srinagar District', 'Baramulla District',
       'Jammu District', 'Ganderbal District', 'Udhampur District',
       'Bandipore District', 'Reasi District', 'Shopian District',
       'Poonch District', 'Kathua District', 'Kishtwar District',
       'Pulwama District', 'Ramban District', 'Rajouri District',
       'Kulgam District', 'Budgam District', 'Anantnag District',
       'Kupwara District', 'Ramgarh District', 'Ranchi District',
       'East Singhbhum District', 'Jamtara District', 'Dumka District',
       'Koderma District', 'Hazaribagh District', 'Simdega District',
       'Garhwa District', 'Saraikela Kharsawan District',
       'Gumla District', 'Chatra District', 'Khunti District',
       'Dhanbad District', 'Godda District', 'Deoghar District',
       'Palamu District', 'Latehar District', 'West Singhbhum District',
       'Pakur District', 'Lohardaga District', 'Sahebganj District',
       'Giridih District', 'Bokaro District', 'Mysuru District',
       'Chitradurga District', 'Kalaburagi District',
       'Ramanagara District', 'Mandya District', 'Kodagu District',
       'Chikkamagaluru District', 'Haveri District', 'Ballari District',
       'Belagavi District', 'Kolar District', 'Uttara Kannada District',
       'Tumakuru District', 'Yadgir District', 'Bengaluru Urban District',
       'Chikkaballapura District', 'Davanagere District',
       'Bagalkote District', 'Vijayapura District', 'Koppal District',
       'Bidar District', 'Bengaluru Rural District', 'Raichur District',
       'Chamarajanagara District', 'Dakshina Kannada District',
       'Hassan District', 'Dharwad District', 'Shivamogga District',
       'Udupi District', 'Gadag District', 'Thiruvananthapuram District',
       'Kasaragod District', 'Malappuram District',
       'Pathanamthitta District', 'Wayanad District',
       'Alappuzha District', 'Kozhikode District', 'Kollam District',
       'Thrissur District', 'Palakkad District', 'Kannur District',
       'Kottayam District', 'Ernakulam District', 'Idukki District',
       'Kargil District', 'Leh Ladakh District', 'Lakshadweep District',
       'Morena District', 'Alirajpur District', 'Sehore District',
       'Rajgarh District', 'Khargone District', 'Satna District',
       'Narsinghpur District', 'Jabalpur District',
       'Hoshangabad District', 'Vidisha District', 'Balaghat District',
       'Singrauli District', 'Betul District', 'Sidhi District',
       'Datia District', 'Dewas District', 'Sheopur District',
       'Neemuch District', 'Raisen District', 'Mandsaur District',
       'Barwani District', 'Katni District', 'Dindori District',
       'Shivpuri District', 'Gwalior District', 'Anuppur District',
       'Agar Malwa District', 'Ashoknagar District', 'Sagar District',
       'Niwari District', 'Rewa District', 'Shajapur District',
       'Ujjain District', 'Bhind District', 'Tikamgarh District',
       'Seoni District', 'Harda District', 'Burhanpur District',
       'Damoh District', 'Bhopal District', 'Jhabua District',
       'Dhar District', 'Guna District', 'East Nimar District',
       'Chhindwara District', 'Umaria District', 'Mandla District',
       'Indore District', 'Shahdol District', 'Ratlam District',
       'Panna District', 'Chhatarpur District', 'Jalgaon District',
       'Latur District', 'Thane District', 'Bhandara District',
       'Nandurbar District', 'Chandrapur District', 'Kolhapur District',
       'Solapur District', 'Mumbai District', 'Sindhudurg District',
       'Dhule District', 'Wardha District', 'Parbhani District',
       'Mumbai Suburban District', 'Hingoli District',
       'Ratnagiri District', 'Nanded District', 'Osmanabad District',
       'Nagpur District', 'Buldhana District', 'Nashik District',
       'Akola District', 'Yavatmal District', 'Amravati District',
       'Washim District', 'Sangli District', 'Gadchiroli District',
       'Raigad District', 'Palghar District', 'Jalna District',
       'Gondia District', 'Ahmednagar District', 'Pune District',
       'Beed District', 'Satara District', 'Kangpokpi District',
       'Noney District', 'Imphal East District', 'Thoubal District',
       'Kakching District', 'Jiribam District', 'Ukhrul District',
       'Tamenglong District', 'Kamjong District', 'Chandel District',
       'Bishnupur District', 'Senapati District', 'Pherzawl District',
       'Churachandpur District', 'Tengnoupal District',
       'Imphal West District', 'North Garo Hills District',
       'South West Khasi Hills District', 'West Garo Hills District',
       'South Garo Hills District', 'East Jaintia Hills District',
       'South West Garo Hills District', 'East Khasi Hills District',
       'East Garo Hills District', 'Ribhoi District',
       'West Jaintia Hills District', 'West Khasi Hills District',
       'Serchhip District', 'Aizawl District', 'Lunglei District',
       'Mamit District', 'Lawngtlai District', 'Kolasib District',
       'Champhai District', 'Saiha District', 'Mon District',
       'Phek District', 'Longleng District', 'Mokokchung District',
       'Kiphire District', 'Kohima District', 'Tuensang District',
       'Peren District', 'Dimapur District', 'Zunheboto District',
       'Wokha District', 'Rayagada District', 'Koraput District',
       'Malkangiri District', 'Sambalpur District', 'Kalahandi District',
       'Anugul District', 'Ganjam District', 'Jajapur District',
       'Bargarh District', 'Dhenkanal District', 'Bhadrak District',
       'Nuapada District', 'Kendujhar District', 'Mayurbhanj District',
       'Jharsuguda District', 'Kandhamal District', 'Deogarh District',
       'Sundargarh District', 'Jagatsinghapur District',
       'Balangir District', 'Baleshwar District', 'Puri District',
       'Sonepur District', 'Khordha District', 'Boudh District',
       'Gajapati District', 'Nayagarh District', 'Nabarangpur District',
       'Kendrapara District', 'Cuttack District', 'Karaikal District',
       'Puducherry District', 'Yanam District', 'Mahe District',
       'Shahid Bhagat Singh Nagar District', 'Fazilka District',
       'Barnala District', 'Mansa District', 'Ludhiana District',
       'Sri Muktsar Sahib District', 'Patiala District',
       'Pathankot District', 'Fatehgarh Sahib District',
       'Rupnagar District', 'Tarn Taran District', 'Sas Nagar District',
       'Sangrur District', 'Jalandhar District', 'Bathinda District',
       'Kapurthala District', 'Firozepur District', 'Gurdaspur District',
       'Amritsar District', 'Faridkot District', 'Hoshiarpur District',
       'Moga District', 'Pali District', 'Ganganagar District',
       'Churu District', 'Jaipur District', 'Baran District',
       'Bhilwara District', 'Banswara District', 'Dungarpur District',
       'Tonk District', 'Jodhpur District', 'Karauli District',
       'Udaipur District', 'Dausa District', 'Nagaur District',
       'Bharatpur District', 'Barmer District', 'Ajmer District',
       'Chittorgarh District', 'Hanumangarh District',
       'Pratapgarh District', 'Sawai Madhopur District',
       'Jalore District', 'Bikaner District', 'Sikar District',
       'Dholpur District', 'Sirohi District', 'Rajsamand District',
       'Jaisalmer District', 'Bundi District', 'Jhalawar District',
       'Alwar District', 'Kota District', 'Jhunjhunu District',
       'Tiruchirappalli District', 'Ramanathapuram District',
       'Krishnagiri District', 'Cuddalore District',
       'Kancheepuram District', 'Tiruppur District',
       'Dharmapuri District', 'Thoothukkudi District',
       'Thanjavur District', 'Madurai District',
       'Tiruvannamalai District', 'Salem District',
       'Nagapattinam District', 'Tirupathur District',
       'Ariyalur District', 'Chennai District', 'The Nilgiris District',
       'Erode District', 'Karur District', 'Kallakkurichi District',
       'Viluppuram District', 'Pudukkottai District',
       'Perambalur District', 'Coimbatore District',
       'Virudhunagar District', 'Dindigul District', 'Sivaganga District',
       'Tenkasi District', 'Chengalpattu District',
       'Kanniyakumari District', 'Tirunelveli District',
       'Thiruvallur District', 'Theni District', 'Ranipet District',
       'Namakkal District', 'Vellore District', 'Thiruvarur District',
       'Narayanpet District', 'Nalgonda District', 'Jangaon District',
       'Bhadradri Kothagudem District', 'Warangal Rural District',
       'Kumuram Bheem Asifabad District', 'Nizamabad District',
       'Adilabad District', 'Rajanna Sircilla District',
       'Nagarkurnool District', 'Peddapalle District', 'Nirmal District',
       'Mahabubabad District', 'Sangareddy District',
       'Wanaparthy District', 'Vikarabad District', 'Jagtial District',
       'Yadadri Bhuvanagiri District', 'Medak District',
       'Mahbubnagar District', 'Jaya Shankar Bhalupally District',
       'Warangal Urban District', 'Rangareddy District',
       'Hyderabad District', 'Suryapet District',
       'Jogulamba Gadwal District', 'Kamareddy District',
       'Mulugu District', 'Medchal Malkajgiri District',
       'Karimnagar District', 'Mancherial District', 'Siddipet District',
       'Khammam District', 'Unakoti District', 'Khowai District',
       'Sepahijala District', 'North Tripura District', 'Dhalai District',
       'South Tripura District', 'Gomati District',
       'West Tripura District', 'Amethi District',
       'Siddharthnagar District', 'Auraiya District', 'Sambhal District',
       'Kanpur Nagar District', 'Aligarh District', 'Mahoba District',
       'Lucknow District', 'Sant Kabeer Nagar District',
       'Hathras District', 'Budaun District', 'Moradabad District',
       'Kushinagar District', 'Baghpat District', 'Shahjahanpur District',
       'Muzaffarnagar District', 'Ambedkar Nagar District',
       'Bahraich District', 'Jalaun District', 'Rampur District',
       'Ballia District', 'Shravasti District', 'Kasganj District',
       'Varanasi District', 'Gautam Buddha Nagar District',
       'Basti District', 'Shamli District', 'Maharajganj District',
       'Etawah District', 'Etah District', 'Banda District',
       'Bijnor District', 'Hardoi District', 'Amroha District',
       'Pilibhit District', 'Mainpuri District', 'Kanpur Dehat District',
       'Jaunpur District', 'Kaushambi District', 'Hapur District',
       'Meerut District', 'Mathura District', 'Chitrakoot District',
       'Lalitpur District', 'Mau District', 'Mirzapur District',
       'Bulandshahr District', 'Gonda District', 'Jhansi District',
       'Chandauli District', 'Bhadohi District', 'Saharanpur District',
       'Bara Banki District', 'Bareilly District', 'Sitapur District',
       'Sultanpur District', 'Agra District', 'Fatehpur District',
       'Rae Bareli District', 'Firozabad District', 'Kheri District',
       'Gorakhpur District', 'Unnao District', 'Prayagraj District',
       'Sonbhadra District', 'Ghazipur District', 'Farrukhabad District',
       'Kannauj District', 'Azamgarh District', 'Ayodhya District',
       'Deoria District', 'Ghaziabad District', 'Bageshwar District',
       'Udham Singh Nagar District', 'Haridwar District',
       'Champawat District', 'Nainital District', 'Dehradun District',
       'Chamoli District', 'Almora District', 'Uttarkashi District',
       'Pithoragarh District', 'Rudraprayag District',
       'Pauri Garhwal District', 'Tehri Garhwal District',
       'South Twenty Four Parganas District', 'Purba Bardhaman District',
       'Uttar Dinajpur District', 'Kalimpong District',
       'Murshidabad District', 'Paschim Medinipur District',
       'Dakshin Dinajpur District', 'Jalpaiguri District',
       'Purulia District', 'North Twenty Four Parganas District',
       'Bankura District', 'Jhargram District', 'Howrah District',
       'Hooghly District', 'Kolkata District', 'Koch Bihar District',
       'Alipurduar District', 'Paschim Bardhaman District',
       'Nadia District', 'Birbhum District', 'Purba Medinipur District',
       'Maldah District', 'Darjiling District'], dtype=object)

In [ ]:
Map_Trans

,State,Year,Quarter,District,Transaction_Count,Transaction_Amount
0,Andaman & Nicobar Islands,2018,1,North And Middle Andaman District,442,9.316631e+05
1,Andaman & Nicobar Islands,2018,1,South Andaman District,5688,1.256025e+07
2,Andaman & Nicobar Islands,2018,1,Nicobars District,528,1.139849e+06
3,Andaman & Nicobar Islands,2018,2,North And Middle Andaman District,825,1.317863e+06
4,Andaman & Nicobar Islands,2018,2,South Andaman District,9395,2.394824e+07
...,...,...,...,...,...,...
17559,West Bengal,2023,4,Nadia District,36242432,6.879568e+10
17560,West Bengal,2023,4,Birbhum District,20708496,3.690499e+10
17561,West Bengal,2023,4,Purba Medinipur District,40572042,7.981990e+10
17562,West Bengal,2023,4,Maldah District,34654950,6.416729e+10
17563,West Bengal,2023,4,Darjiling District,16807885,2.793986e+10

In [8]:
#Map_user

Path3 = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/map/user/hover/country/india/state/"
Map_user_list = os.listdir(Path3)

# Initialize the dictionary to store the data
clm3 = {"State": [], "Year": [], "Quarter": [], "District": [], "RegisteredUsers": [], "AppOpens": []}

# Loop through the State
for state in Map_user_list:
    state_list=Path3+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Map_User_Data = json.load(JF)

            for i in Map_User_Data["data"]["hoverData"].items():
                district=i[0]
                registeredUsers=i[1]["registeredUsers"]
                appOpens=i[1]["appOpens"]
                clm3["District"].append(district)
                clm3["RegisteredUsers"].append(registeredUsers)
                clm3["AppOpens"].append(appOpens)
                clm3["State"].append(state)
                clm3["Year"].append(year)
                clm3["Quarter"].append(int(jfile.strip(".json")))

Map_User=pd.DataFrame(clm3)
Map_User["State"]=Map_User["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Map_User["State"]=Map_User["State"].str.replace("-", " ")
Map_User["State"]=Map_User["State"].str.title()
Map_User["District"]=Map_User["District"].str.title()
Map_User["State"]=Map_User["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Map_User["District"].unique()

array(['north and middle andaman district', 'south andaman district',
       'nicobars district', 'east godavari district',
       'srikakulam district', 'visakhapatnam district',
       'prakasam district', 'anantapur district', 'kurnool district',
       'guntur district', 'krishna district', 'spsr nellore district',
       'vizianagaram district', 'ysr district', 'west godavari district',
       'chittoor district', 'lower subansiri district', 'tirap district',
       'papum pare district', 'anjaw district', 'lower siang district',
       'dibang valley district', 'west kameng district',
       'shi yomi district', 'east kameng district', 'lohit district',
       'lepa rada district', 'lower dibang valley district',
       'longding district', 'west siang district', 'kamle district',
       'upper siang district', 'kurung kumey district', 'siang district',
       'kra daadi district', 'changlang district',
       'pakke kessang district', 'east siang district',
       'upper subansiri district', 'tawang district', 'namsai district',
       'tinsukia district', 'lakhimpur district', 'kamrup district',
       'kokrajhar district', 'karbi anglong district',
       'sivasagar district', 'dibrugarh district',
       'south salmara mancachar district', 'nagaon district',
       'dhubri district', 'golaghat district', 'udalguri district',
       'majuli district', 'sonitpur district', 'hojai district',
       'marigaon district', 'chirang district', 'cachar district',
       'nalbari district', 'west karbi anglong district',
       'dhemaji district', 'karimganj district', 'bongaigaon district',
       'dima hasao district', 'baksa district', 'charaideo district',
       'darrang district', 'kamrup metropolitan district',
       'hailakandi district', 'barpeta district', 'goalpara district',
       'biswanath district', 'jorhat district', 'madhepura district',
       'purnia district', 'nalanda district', 'buxar district',
       'darbhanga district', 'nawada district', 'jamui district',
       'sheikhpura district', 'siwan district', 'muzaffarpur district',
       'patna district', 'jehanabad district', 'rohtas district',
       'begusarai district', 'supaul district', 'sitamarhi district',
       'saran district', 'arwal district', 'vaishali district',
       'pashchim champaran district', 'gopalganj district',
       'lakhisarai district', 'aurangabad district',
       'kaimur bhabua district', 'araria district', 'munger district',
       'katihar district', 'khagaria district', 'saharsa district',
       'bhagalpur district', 'madhubani district', 'kishanganj district',
       'gaya district', 'samastipur district', 'banka district',
       'purbi champaran district', 'sheohar district', 'bhojpur district',
       'chandigarh district', 'dhamtari district', 'korba district',
       'surajpur district', 'baloda bazar district', 'sukma district',
       'raigarh district', 'janjgir champa district', 'jashpur district',
       'balod district', 'kabirdham district', 'surguja district',
       'dantewada district', 'gariyaband district', 'durg district',
       'rajnandgaon district', 'raipur district', 'narayanpur district',
       'kanker district', 'korea district', 'mungeli district',
       'bilaspur district', 'balrampur district', 'bijapur district',
       'bemetara district', 'bastar district', 'kondagaon district',
       'mahasamund district', 'diu district', 'daman district',
       'dadra and nagar haveli district', 'south district',
       'central district', 'new delhi district', 'west district',
       'south west district', 'south east delhi district',
       'shahdara district', 'north east district', 'east district',
       'north west district', 'north district', 'north goa district',
       'south goa district', 'anand district', 'jamnagar district',
       'devbhumi dwarka district', 'rajkot district',
       'aravallis district', 'chhotaudepur district', 'botad district',
       'bharuch district', 'bhavnagar district', 'junagadh district',
       'mahesana district', 'the dangs district', 'kheda district',
       'surat district', 'porbandar district', 'gandhinagar district',
       'panch mahals district', 'narmada district',
       'gir somnath district', 'valsad district', 'mahisagar district',
       'sabar kantha district', 'tapi district', 'vadodara district',
       'banas kantha district', 'amreli district', 'ahmadabad district',
       'dohad district', 'navsari district', 'patan district',
       'kachchh district', 'surendranagar district', 'morbi district',
       'yamunanagar district', 'sonipat district', 'jind district',
       'rohtak district', 'faridabad district', 'mahendragarh district',
       'hisar district', 'karnal district', 'fatehabad district',
       'palwal district', 'charkhi dadri district', 'ambala district',
       'rewari district', 'panchkula district', 'bhiwani district',
       'sirsa district', 'mewat district', 'panipat district',
       'gurugram district', 'kaithal district', 'kurukshetra district',
       'jhajjar district', 'solan district', 'sirmaur district',
       'shimla district', 'hamirpur district', 'una district',
       'kangra district', 'kullu district', 'mandi district',
       'lahul and spiti district', 'chamba district', 'kinnaur district',
       'muzaffarabad district', 'doda district', 'samba district',
       'mirpur district', 'srinagar district', 'baramulla district',
       'jammu district', 'ganderbal district', 'udhampur district',
       'bandipore district', 'reasi district', 'shopian district',
       'poonch district', 'kathua district', 'kishtwar district',
       'pulwama district', 'ramban district', 'rajouri district',
       'kulgam district', 'budgam district', 'anantnag district',
       'kupwara district', 'ramgarh district', 'ranchi district',
       'east singhbhum district', 'jamtara district', 'dumka district',
       'koderma district', 'hazaribagh district', 'simdega district',
       'garhwa district', 'saraikela kharsawan district',
       'gumla district', 'chatra district', 'khunti district',
       'dhanbad district', 'godda district', 'deoghar district',
       'palamu district', 'latehar district', 'west singhbhum district',
       'pakur district', 'lohardaga district', 'sahebganj district',
       'giridih district', 'bokaro district', 'mysuru district',
       'chitradurga district', 'kalaburagi district',
       'ramanagara district', 'mandya district', 'kodagu district',
       'chikkamagaluru district', 'haveri district', 'ballari district',
       'belagavi district', 'kolar district', 'uttara kannada district',
       'tumakuru district', 'yadgir district', 'bengaluru urban district',
       'chikkaballapura district', 'davanagere district',
       'bagalkote district', 'vijayapura district', 'koppal district',
       'bidar district', 'bengaluru rural district', 'raichur district',
       'chamarajanagara district', 'dakshina kannada district',
       'hassan district', 'dharwad district', 'shivamogga district',
       'udupi district', 'gadag district', 'thiruvananthapuram district',
       'kasaragod district', 'malappuram district',
       'pathanamthitta district', 'wayanad district',
       'alappuzha district', 'kozhikode district', 'kollam district',
       'thrissur district', 'palakkad district', 'kannur district',
       'kottayam district', 'ernakulam district', 'idukki district',
       'kargil district', 'leh ladakh district', 'lakshadweep district',
       'morena district', 'alirajpur district', 'sehore district',
       'rajgarh district', 'khargone district', 'satna district',
       'narsinghpur district', 'jabalpur district',
       'hoshangabad district', 'vidisha district', 'balaghat district',
       'singrauli district', 'betul district', 'sidhi district',
       'datia district', 'dewas district', 'sheopur district',
       'neemuch district', 'raisen district', 'mandsaur district',
       'barwani district', 'katni district', 'dindori district',
       'shivpuri district', 'gwalior district', 'anuppur district',
       'agar malwa district', 'ashoknagar district', 'sagar district',
       'niwari district', 'rewa district', 'shajapur district',
       'ujjain district', 'bhind district', 'tikamgarh district',
       'seoni district', 'harda district', 'burhanpur district',
       'damoh district', 'bhopal district', 'jhabua district',
       'dhar district', 'guna district', 'east nimar district',
       'chhindwara district', 'umaria district', 'mandla district',
       'indore district', 'shahdol district', 'ratlam district',
       'panna district', 'chhatarpur district', 'jalgaon district',
       'latur district', 'thane district', 'bhandara district',
       'nandurbar district', 'chandrapur district', 'kolhapur district',
       'solapur district', 'mumbai district', 'sindhudurg district',
       'dhule district', 'wardha district', 'parbhani district',
       'mumbai suburban district', 'hingoli district',
       'ratnagiri district', 'nanded district', 'osmanabad district',
       'nagpur district', 'buldhana district', 'nashik district',
       'akola district', 'yavatmal district', 'amravati district',
       'washim district', 'sangli district', 'gadchiroli district',
       'raigad district', 'palghar district', 'jalna district',
       'gondia district', 'ahmednagar district', 'pune district',
       'beed district', 'satara district', 'kangpokpi district',
       'noney district', 'imphal east district', 'thoubal district',
       'kakching district', 'jiribam district', 'ukhrul district',
       'tamenglong district', 'kamjong district', 'chandel district',
       'bishnupur district', 'senapati district', 'pherzawl district',
       'churachandpur district', 'tengnoupal district',
       'imphal west district', 'north garo hills district',
       'south west khasi hills district', 'west garo hills district',
       'south garo hills district', 'east jaintia hills district',
       'south west garo hills district', 'east khasi hills district',
       'east garo hills district', 'ribhoi district',
       'west jaintia hills district', 'west khasi hills district',
       'serchhip district', 'aizawl district', 'lunglei district',
       'mamit district', 'lawngtlai district', 'kolasib district',
       'champhai district', 'saiha district', 'mon district',
       'phek district', 'longleng district', 'mokokchung district',
       'kiphire district', 'kohima district', 'tuensang district',
       'peren district', 'dimapur district', 'zunheboto district',
       'wokha district', 'rayagada district', 'koraput district',
       'malkangiri district', 'sambalpur district', 'kalahandi district',
       'anugul district', 'ganjam district', 'jajapur district',
       'bargarh district', 'dhenkanal district', 'bhadrak district',
       'nuapada district', 'kendujhar district', 'mayurbhanj district',
       'jharsuguda district', 'kandhamal district', 'deogarh district',
       'sundargarh district', 'jagatsinghapur district',
       'balangir district', 'baleshwar district', 'puri district',
       'sonepur district', 'khordha district', 'boudh district',
       'gajapati district', 'nayagarh district', 'nabarangpur district',
       'kendrapara district', 'cuttack district', 'karaikal district',
       'puducherry district', 'yanam district', 'mahe district',
       'shahid bhagat singh nagar district', 'fazilka district',
       'barnala district', 'mansa district', 'ludhiana district',
       'sri muktsar sahib district', 'patiala district',
       'pathankot district', 'fatehgarh sahib district',
       'rupnagar district', 'tarn taran district', 'sas nagar district',
       'sangrur district', 'jalandhar district', 'bathinda district',
       'kapurthala district', 'firozepur district', 'gurdaspur district',
       'amritsar district', 'faridkot district', 'hoshiarpur district',
       'moga district', 'pali district', 'ganganagar district',
       'churu district', 'jaipur district', 'baran district',
       'bhilwara district', 'banswara district', 'dungarpur district',
       'tonk district', 'jodhpur district', 'karauli district',
       'udaipur district', 'dausa district', 'nagaur district',
       'bharatpur district', 'barmer district', 'ajmer district',
       'chittorgarh district', 'hanumangarh district',
       'pratapgarh district', 'sawai madhopur district',
       'jalore district', 'bikaner district', 'sikar district',
       'dholpur district', 'sirohi district', 'rajsamand district',
       'jaisalmer district', 'bundi district', 'jhalawar district',
       'alwar district', 'kota district', 'jhunjhunu district',
       'tiruchirappalli district', 'ramanathapuram district',
       'krishnagiri district', 'cuddalore district',
       'kancheepuram district', 'tiruppur district',
       'dharmapuri district', 'thoothukkudi district',
       'thanjavur district', 'madurai district',
       'tiruvannamalai district', 'salem district',
       'nagapattinam district', 'tirupathur district',
       'ariyalur district', 'chennai district', 'the nilgiris district',
       'erode district', 'karur district', 'kallakkurichi district',
       'viluppuram district', 'pudukkottai district',
       'perambalur district', 'coimbatore district',
       'virudhunagar district', 'dindigul district', 'sivaganga district',
       'tenkasi district', 'chengalpattu district',
       'kanniyakumari district', 'tirunelveli district',
       'thiruvallur district', 'theni district', 'ranipet district',
       'namakkal district', 'vellore district', 'thiruvarur district',
       'narayanpet district', 'nalgonda district', 'jangaon district',
       'bhadradri kothagudem district', 'warangal rural district',
       'kumuram bheem asifabad district', 'nizamabad district',
       'adilabad district', 'rajanna sircilla district',
       'nagarkurnool district', 'peddapalle district', 'nirmal district',
       'mahabubabad district', 'sangareddy district',
       'wanaparthy district', 'vikarabad district', 'jagtial district',
       'yadadri bhuvanagiri district', 'medak district',
       'mahbubnagar district', 'jaya shankar bhalupally district',
       'warangal urban district', 'rangareddy district',
       'hyderabad district', 'suryapet district',
       'jogulamba gadwal district', 'kamareddy district',
       'mulugu district', 'medchal malkajgiri district',
       'karimnagar district', 'mancherial district', 'siddipet district',
       'khammam district', 'unakoti district', 'khowai district',
       'sepahijala district', 'north tripura district', 'dhalai district',
       'south tripura district', 'gomati district',
       'west tripura district', 'amethi district',
       'siddharthnagar district', 'auraiya district', 'sambhal district',
       'kanpur nagar district', 'aligarh district', 'mahoba district',
       'lucknow district', 'sant kabeer nagar district',
       'hathras district', 'budaun district', 'moradabad district',
       'kushinagar district', 'baghpat district', 'shahjahanpur district',
       'muzaffarnagar district', 'ambedkar nagar district',
       'bahraich district', 'jalaun district', 'rampur district',
       'ballia district', 'shravasti district', 'kasganj district',
       'varanasi district', 'gautam buddha nagar district',
       'basti district', 'shamli district', 'maharajganj district',
       'etawah district', 'etah district', 'banda district',
       'bijnor district', 'hardoi district', 'amroha district',
       'pilibhit district', 'mainpuri district', 'kanpur dehat district',
       'jaunpur district', 'kaushambi district', 'hapur district',
       'meerut district', 'mathura district', 'chitrakoot district',
       'lalitpur district', 'mau district', 'mirzapur district',
       'bulandshahr district', 'gonda district', 'jhansi district',
       'chandauli district', 'bhadohi district', 'saharanpur district',
       'bara banki district', 'bareilly district', 'sitapur district',
       'sultanpur district', 'agra district', 'fatehpur district',
       'rae bareli district', 'firozabad district', 'kheri district',
       'gorakhpur district', 'unnao district', 'prayagraj district',
       'sonbhadra district', 'ghazipur district', 'farrukhabad district',
       'kannauj district', 'azamgarh district', 'ayodhya district',
       'deoria district', 'ghaziabad district',
       'udham singh nagar district', 'haridwar district',
       'almora district', 'pithoragarh district', 'rudraprayag district',
       'pauri garhwal district', 'bageshwar district',
       'champawat district', 'nainital district', 'dehradun district',
       'chamoli district', 'uttarkashi district',
       'tehri garhwal district', 'south twenty four parganas district',
       'purba bardhaman district', 'uttar dinajpur district',
       'kalimpong district', 'murshidabad district',
       'paschim medinipur district', 'dakshin dinajpur district',
       'jalpaiguri district', 'purulia district',
       'north twenty four parganas district', 'bankura district',
       'jhargram district', 'howrah district', 'hooghly district',
       'kolkata district', 'koch bihar district', 'alipurduar district',
       'paschim bardhaman district', 'nadia district', 'birbhum district',
       'purba medinipur district', 'maldah district',
       'darjiling district'], dtype=object)

In [ ]:
Map_User

,State,Year,Quarter,District,RegisteredUsers,AppOpens
0,Andaman & Nicobar Islands,2018,1,North And Middle Andaman District,632,0
1,Andaman & Nicobar Islands,2018,1,South Andaman District,5846,0
2,Andaman & Nicobar Islands,2018,1,Nicobars District,262,0
3,Andaman & Nicobar Islands,2018,2,North And Middle Andaman District,911,0
4,Andaman & Nicobar Islands,2018,2,South Andaman District,8143,0
...,...,...,...,...,...,...
17563,West Bengal,2023,4,Nadia District,1603527,67224546
17564,West Bengal,2023,4,Birbhum District,1013025,52281841
17565,West Bengal,2023,4,Purba Medinipur District,1589203,69991821
17566,West Bengal,2023,4,Maldah District,1134600,88292475
17567,West Bengal,2023,4,Darjiling District,660231,39079247

In [9]:

#Top_trans

Path4 = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/top/transaction/country/india/state/"
Top_Trans_list = os.listdir(Path4)

# Initialize the dictionary to store the data
clm3 = {"State": [], "Year": [], "Quarter": [], "Pincodes": [], "Transaction_count": [], "Transaction_amount": []}

# Loop through the states
for state in Top_Trans_list:
    state_list=Path4+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Top_trans_Data = json.load(JF)

            for i in Top_trans_Data["data"]["pincodes"]:
                entityName=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                clm3["Pincodes"].append(entityName)
                clm3["Transaction_count"].append(count)
                clm3["Transaction_amount"].append(amount)
                clm3["State"].append(state)
                clm3["Year"].append(year)
                clm3["Quarter"].append(int(jfile.strip(".json")))

Top_trans=pd.DataFrame(clm3)
Top_trans["State"]=Top_trans["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Top_trans["State"]=Top_trans["State"].str.replace("-", " ")
Top_trans["State"]=Top_trans["State"].str.title()
Top_trans["State"]=Top_trans["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Top_trans

,State,Year,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar Islands,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar Islands,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar Islands,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar Islands,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar Islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
8562,West Bengal,2023,4,721301,4133775,5.718222e+09
8563,West Bengal,2023,4,700001,3983241,8.039689e+09
8564,West Bengal,2023,4,732125,3950411,6.557345e+09
8565,West Bengal,2023,4,700039,3742452,5.608622e+09
8566,West Bengal,2023,4,700014,3652710,6.184795e+09

In [10]:
#Top_user

Path5 = "E:/Guvi_Data_Science/MDT33/Capstone_Project/.venv/Phonepae/pulse/data/top/user/country/india/state/"
Top_User_list = os.listdir(Path5)

# Initialize the dictionary to store the data
clm4 = {"State": [], "Year": [], "Quarter": [], "Pincodes": [], "RegisteredUsers": []}

# Loop through the states
for state in Top_User_list:
    state_list=Path5+state+"/"
    year_list= os.listdir(state_list)

    # Loop through the years
    for year in year_list:
        cur_year=state_list+year+"/"
        jfiles = os.listdir(cur_year)

        # Loop through the json files
        for jfile in jfiles:
            jfiles_list=cur_year+jfile
            
            # Open the data file
            JF =open(jfiles_list, "r")
            Top_user_Data = json.load(JF)


            for i in Top_user_Data["data"]["pincodes"]:
                name=i["name"]
                registeredUsers=i["registeredUsers"]
                clm4["Pincodes"].append(name)
                clm4["RegisteredUsers"].append(registeredUsers)
                clm4["State"].append(state)
                clm4["Year"].append(year)
                clm4["Quarter"].append(int(jfile.strip(".json")))


Top_user=pd.DataFrame(clm4)
Top_user["State"]=Top_user["State"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar Islands")
Top_user["State"]=Top_user["State"].str.replace("-", " ")
Top_user["State"]=Top_user["State"].str.title()
Top_user["State"]=Top_user["State"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
Top_user

                          State  Year  Quarter Pincodes  RegisteredUsers
0     Andaman & Nicobar Islands  2018        1   744103             1608
1     Andaman & Nicobar Islands  2018        1   744101             1108
2     Andaman & Nicobar Islands  2018        1   744105             1075
3     Andaman & Nicobar Islands  2018        1   744102             1006
4     Andaman & Nicobar Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
8563                West Bengal  2023        4   700015           126663
8564                West Bengal  2023        4   742304           123320
8565                West Bengal  2023        4   721101           123088
8566                West Bengal  2023        4   700150           119283
8567                West Bengal  2023        4   700091           118578

[8568 rows x 5 columns]

In [ ]:
#SQL Table for Agg_Trans 
connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_1 = ("""Create table if not exists Agg_Trans(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            Transaction_type VARCHAR(255),
                                                            Transaction_Count bigint,
                                                            Transaction_Amount bigint)""")
cursor.execute(create_query_1)
connection.commit()

Insert_Query1 = "INSERT INTO Agg_Trans (State, Year, Quarter, Transaction_type, Transaction_Count, Transaction_Amount) VALUES (%s,%s,%s,%s,%s,%s)"
val = Agg_Trans.values.tolist()
cursor.executemany(Insert_Query1, val)
connection.commit()
print(cursor.rowcount, "Agg_Trans Table created.")

4314 Agg_Trans Table created.

In [ ]:
#SQL Table for Agg_user

connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_2 = ("""Create table if not exists Agg_user(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            Brand VARCHAR(255),
                                                            Transaction_Count bigint,
                                                            Percentage decimal(5,2))""")
cursor.execute(create_query_2)
connection.commit()
Insert_Query2 = "INSERT INTO Agg_user(State, Year, Quarter, Brand, Transaction_Count, Percentage) VALUES (%s,%s,%s,%s,%s,%s)"
val = Agg_user.values.tolist()
cursor.executemany(Insert_Query2, val)
connection.commit()
print(cursor.rowcount, "Agg_user Table created.")

6732 Agg_user Table created.

In [ ]:
#SQL Table for Map_trans

connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_3 = ("""Create table if not exists Map_Trans(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            District VARCHAR(255),
                                                            Transaction_Count bigint,
                                                            Transaction_Amount bigint)""")
cursor.execute(create_query_3)
connection.commit()

Insert_Query3 = "INSERT INTO Map_Trans (State, Year, Quarter, District, Transaction_Count, Transaction_Amount) VALUES (%s,%s,%s,%s,%s,%s)"
val = Map_Trans.values.tolist()
cursor.executemany(Insert_Query3, val)
connection.commit()
print(cursor.rowcount, "Map_Trans Table created.")

17564 Map_Trans Table created.

In [ ]:
##SQL Table for Map_User

connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_4 = ("""Create table if not exists Map_User(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            District VARCHAR(255),
                                                            RegisteredUsers bigint,
                                                            AppOpens bigint)""")
cursor.execute(create_query_4)
connection.commit()

Insert_Query4 = "INSERT INTO Map_User (State, Year, Quarter, District, RegisteredUsers, AppOpens) VALUES (%s,%s,%s,%s,%s,%s)"
val = Map_User.values.tolist()
cursor.executemany(Insert_Query4, val)
connection.commit()
print(cursor.rowcount, "Map_User Table created.")

17568 Map_User Table created.

In [ ]:
##SQL Table for Top_Trans

connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_5 = ("""Create table if not exists Top_Trans(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            Pincode VARCHAR(255),
                                                            Transaction_count bigint,
                                                            Transaction_amount bigint)""")
cursor.execute(create_query_5)
connection.commit()

Insert_Query5 = "INSERT INTO Top_Trans (State, Year, Quarter, Pincode, Transaction_count, Transaction_amount) VALUES (%s,%s,%s,%s,%s,%s)"
val = Top_trans.values.tolist()
cursor.executemany(Insert_Query5, val)
connection.commit()
print(cursor.rowcount, "Top_trans Table created.")

8567 Top_trans Table created.

In [ ]:
##SQL Table for Top_user

connection = sql.connect(
                    host="localhost",
                    user="root",
                    password="Nisama@2021",
                    database="phonepae")
                
cursor=connection.cursor()
create_query_6 = ("""Create table if not exists Top_user(State VARCHAR(100),  
                                                            Year INT,
                                                            Quarter INT,
                                                            Pincode VARCHAR(255),
                                                            RegisteredUsers bigint)""")
cursor.execute(create_query_6)
connection.commit()

Insert_Query6 = "INSERT INTO Top_user (State, Year, Quarter, Pincode, RegisteredUsers) VALUES (%s,%s,%s,%s,%s)"
val = Top_user.values.tolist()
cursor.executemany(Insert_Query6, val)
connection.commit()
print(cursor.rowcount, "Top_user Table created.")

8568 Top_user Table created.

In [ ]:
Top_user

                         States Years  Quarter Pincodes  RegisteredUsers
0     Andaman & Nicobar Islands  2018        1   744103             1608
1     Andaman & Nicobar Islands  2018        1   744101             1108
2     Andaman & Nicobar Islands  2018        1   744105             1075
3     Andaman & Nicobar Islands  2018        1   744102             1006
4     Andaman & Nicobar Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
8563                West Bengal  2023        4   700015           126663
8564                West Bengal  2023        4   742304           123320
8565                West Bengal  2023        4   721101           123088
8566                West Bengal  2023        4   700150           119283
8567                West Bengal  2023        4   700091           118578

[8568 rows x 5 columns]